# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

require_relative '../node_modules/react-native-permissions/scripts/setup'

platform :ios, min_ios_version_supported

prepare_react_native_project!

use_frameworks! :linkage => :static
$RNFirebaseAsStaticFramework = true


config = use_native_modules!


target 'CGXFirstConnect' do

  setup_permissions([
    'Notifications',
  ])

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

end


post_install do |installer|

  react_native_post_install(
    installer,
    config[:reactNativePath],
    :mac_catalyst_enabled => false
  )


  # Xcode 26.x + fmt workaround
  fmt_base = File.join(
    installer.sandbox.root,
    'fmt',
    'include',
    'fmt',
    'base.h'
  )

  if File.exist?(fmt_base)

    content = File.read(fmt_base)

    unless content.include?('Xcode 26 workaround')

      patched = content.gsub(
        /^(#elif defined\(__cpp_consteval\)\n#  define FMT_USE_CONSTEVAL) 1/,
        "// Xcode 26 workaround: disable consteval\n\\1 0"
      )

      if patched != content
        File.chmod(0644, fmt_base)
        File.write(fmt_base, patched)
        puts " Patched fmt for Xcode 26"
      end

    end

  end


  installer.pods_project.targets.each do |target|

    target.build_configurations.each do |build_config|

      if target.name == 'fmt'
        build_config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'gnu++20'
        build_config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
        build_config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '$(inherited) -Wno-error'
      end


      if target.name.include?('RCT-Folly')
        build_config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'gnu++20'
        build_config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
      end

    end

  end

end